import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
type Cell=unknown;type Row=Cell[];
const numeric=(value:unknown)=>value===null||value===undefined||value===""?null:Number(value);
const definitions:Record<string,{filename:string;headers:string[];load:(supabase:Awaited<ReturnType<typeof createClient>>)=>Promise<{data:unknown[]|null;error:unknown}>;map:(row:Record<string,unknown>)=>Row}>={
 rentabilidad:{filename:"rentabilidad-por-lote",headers:["Lote","Costo productor","Costo javas","Costo materiales","Costo mano de obra","Costo flete","Costo directo","Ingresos reales","Ganancia bruta","Javas producidas","Costo por java"],load:s=>s.from("v_rentabilidad_lote").select("*").order("codigo") as never,map:r=>[r.codigo,numeric(r.costo_productor),numeric(r.costo_total_javas),numeric(r.costo_materiales),numeric(r.costo_mano_obra),numeric(r.costo_flete),numeric(r.costo_directo),numeric(r.ingresos_reales),numeric(r.ganancia_bruta),numeric(r.cantidad_enjavada),numeric(r.costo_por_java_producida)]},
 "saldos-clientes":{filename:"saldos-clientes",headers:["Venta","Monto total","Monto cobrado","Saldo pendiente"],load:s=>s.from("v_saldo_venta").select("*").order("codigo") as never,map:r=>[r.codigo,numeric(r.monto_total),numeric(r.monto_pagado),numeric(r.saldo_pendiente)]},
 "saldos-productores":{filename:"saldos-productores",headers:["Lote","Monto productor","Monto pagado","Saldo pendiente"],load:s=>s.from("v_saldo_productor").select("*").order("codigo") as never,map:r=>[r.codigo,numeric(r.monto_productor),numeric(r.monto_pagado),numeric(r.saldo_pendiente)]},
 gastos:{filename:"gastos",headers:["Fecha","Categoría","Concepto","Monto","Medio de pago","Comprobante"],load:s=>s.from("gasto").select("fecha_gasto,concepto,monto,medio_pago,numero_comprobante,categoria_gasto(nombre)").eq("anulado",false).order("fecha_gasto",{ascending:false}) as never,map:r=>[r.fecha_gasto,(r.categoria_gasto as Record<string,unknown>)?.nombre as string,r.concepto,numeric(r.monto),r.medio_pago,r.numero_comprobante]},
 "ventas-clientes":{filename:"ventas-por-cliente",headers:["Venta","Fecha","Cliente","Tipo","Estado","Variedad","Javas","Precio por java","Subtotal"],load:s=>s.from("venta").select("codigo,fecha_venta,tipo,estado,cliente(nombre),detalle_venta(cantidad_javas,precio_java,subtotal,variedad(nombre))").neq("estado","ANULADA").order("fecha_venta",{ascending:false}) as never,map:r=>{const detail=((r.detalle_venta as Record<string,unknown>[])||[])[0]||{};return[r.codigo,r.fecha_venta,(r.cliente as Record<string,unknown>)?.nombre as string,r.tipo,r.estado,(detail.variedad as Record<string,unknown>)?.nombre as string,numeric(detail.cantidad_javas),numeric(detail.precio_java),numeric(detail.subtotal)]}}
};
function safe(value:Cell){if(value===null||value===undefined)return "";if(typeof value==="number")return Number.isFinite(value)?String(value).replace(".",","):"";let text=String(value);if(/^[=+\-@]/.test(text))text=`'${text}`;return /[";\r\n]/.test(text)?`"${text.replaceAll('"','""')}"`:text}
export async function GET(_:Request,{params}:{params:Promise<{report:string}>}){const {report}=await params;const definition=definitions[report];if(!definition)return NextResponse.json({error:"Reporte no encontrado"},{status:404});const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:"Sesión requerida"},{status:401});const result=await definition.load(supabase);if(result.error)return NextResponse.json({error:"No se pudo generar el reporte"},{status:500});const source=(result.data||[]) as Record<string,unknown>[];const rows:Row[]=report==="ventas-clientes"?source.flatMap(record=>{const details=(record.detalle_venta as Record<string,unknown>[])||[];return details.length?details.map(detail=>definition.map({...record,detalle_venta:[detail]})): [definition.map(record)]}):source.map(definition.map);const csv="\uFEFFsep=;\r\n"+[definition.headers,...rows].map(row=>row.map(safe).join(";")).join("\r\n");const date=new Date().toISOString().slice(0,10);return new NextResponse(csv,{headers:{"Content-Type":"text/csv; charset=utf-8","Content-Disposition":`attachment; filename="${definition.filename}-${date}.csv"`,"Cache-Control":"no-store"}})}

