"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
const allowed=new Set(["productor","cliente","trabajador","transportista","material","producto","variedad","motivo_rechazo","categoria_gasto"]);const pathFor:Record<string,string>={productor:"/productores",cliente:"/clientes",trabajador:"/trabajadores",transportista:"/transportistas",material:"/materiales",producto:"/productos",variedad:"/variedades",motivo_rechazo:"/motivos-rechazo",categoria_gasto:"/categorias-gasto"};
async function authenticated(){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Sesión requerida");return {supabase,user}}
async function administrator(){const session=await authenticated();const {data:profile,error}=await session.supabase.from("perfil_usuario").select("rol,activo").eq("id",session.user.id).single();if(error||!profile?.activo||profile.rol!=="ADMINISTRADOR")throw new Error("Esta acción requiere permisos de administrador");return session}
export async function linkUserProfile(formData:FormData){const {supabase}=await administrator();const {error}=await supabase.from("perfil_usuario").insert({id:String(formData.get("id")).trim(),nombre:String(formData.get("nombre")).trim(),rol:String(formData.get("rol")),activo:true});if(error)throw new Error(error.message);revalidatePath("/administracion")}
export async function updateUserProfile(formData:FormData){const {supabase,user}=await administrator();const id=String(formData.get("id"));const active=String(formData.get("activo"))==="true";if(id===user.id&&!active)throw new Error("No puedes desactivar tu propio usuario");const {error}=await supabase.from("perfil_usuario").update({nombre:String(formData.get("nombre")).trim(),rol:String(formData.get("rol")),activo:active}).eq("id",id);if(error)throw new Error(error.message);revalidatePath("/administracion")}
export async function saveMaster(formData:FormData){const table=String(formData.get("table"));if(!allowed.has(table))throw new Error("Tabla no permitida");const {supabase,user}=await authenticated();const payload:Record<string,string|number|null>={nombre:String(formData.get("nombre")||"").trim(),updated_by:user.id};if(["productor","cliente","trabajador","transportista"].includes(table)){payload.numero_documento=String(formData.get("numero_documento")||"").trim()||null;payload.telefono=String(formData.get("telefono")||"").trim()||null}if(["producto","variedad","motivo_rechazo","categoria_gasto"].includes(table))payload.descripcion=String(formData.get("descripcion")||"").trim()||null;if(table==="material"){payload.unidad_medida=String(formData.get("unidad_medida")||"").trim();const cost=String(formData.get("costo_referencia")||"");payload.costo_referencia=cost?Number(cost):null}if(table==="variedad")payload.producto_id=Number(formData.get("producto_id"));const id=String(formData.get("id")||"");const result=id?await supabase.from(table).update(payload).eq("id",id):await supabase.from(table).insert({...payload,created_by:user.id});if(result.error)throw new Error(result.error.message);revalidatePath(pathFor[table])}
export async function toggleMaster(formData:FormData){const table=String(formData.get("table"));if(!allowed.has(table))throw new Error("Tabla no permitida");const {supabase,user}=await authenticated();const {error}=await supabase.from(table).update({activo:String(formData.get("activo"))!=="true",updated_by:user.id}).eq("id",String(formData.get("id")));if(error)throw new Error(error.message);revalidatePath(pathFor[table])}
export async function logout(){const supabase=await createClient();await supabase.auth.signOut();redirect("/login")}
export async function createLot(formData:FormData){const {supabase,user}=await authenticated();const estimated=String(formData.get("cantidad_estimada_javas")||"");const {error}=await supabase.from("lote").insert({productor_id:Number(formData.get("productor_id")),variedad_id:Number(formData.get("variedad_id")),fecha_registro:String(formData.get("fecha_registro")),cantidad_estimada_javas:estimated?Number(estimated):null,observaciones:String(formData.get("observaciones")||"").trim()||null,created_by:user.id,updated_by:user.id});if(error)throw new Error(error.message);revalidatePath("/produccion")}
export async function updateLot(formData:FormData){const {supabase,user}=await authenticated();const {error}=await supabase.from("lote").update({productor_id:Number(formData.get("productor_id")),variedad_id:Number(formData.get("variedad_id")),fecha_registro:String(formData.get("fecha_registro")),cantidad_estimada_javas:Number(formData.get("cantidad_estimada_javas"))||null,observaciones:String(formData.get("observaciones")||"").trim()||null,updated_by:user.id}).eq("id",Number(formData.get("id"))).eq("estado","RECIBIDO");if(error)throw new Error(error.message);revalidatePath("/produccion")}
export async function archiveLot(formData:FormData){const {supabase,user}=await authenticated();const id=Number(formData.get("id"));const {data:production}=await supabase.from("produccion").select("id").eq("lote_id",id).maybeSingle();if(production)throw new Error("No se puede eliminar un lote que ya inició producción");const {data:shipment}=await supabase.from("envio").select("id").eq("lote_id",id).limit(1).maybeSingle();if(shipment)throw new Error("No se puede eliminar un lote con envíos");const {error}=await supabase.from("lote").update({estado:"CERRADO",observaciones:"Lote eliminado desde el ERP",updated_by:user.id}).eq("id",id).eq("estado","RECIBIDO");if(error)throw new Error(error.message);revalidatePath("/produccion")}
export async function startProduction(formData:FormData){const {supabase,user}=await authenticated();const loteId=Number(formData.get("lote_id"));const {data:existing,error:readError}=await supabase.from("produccion").select("id").eq("lote_id",loteId).maybeSingle();if(readError)throw new Error(readError.message);if(!existing){const {error}=await supabase.from("produccion").insert({lote_id:loteId,created_by:user.id,updated_by:user.id});if(error&&error.code!=="23505")throw new Error(error.message)}const {error:updateError}=await supabase.from("lote").update({estado:"EN_PRODUCCION",updated_by:user.id}).eq("id",loteId);if(updateError)throw new Error(updateError.message);revalidatePath("/produccion")}
export async function addProductionMaterial(formData:FormData){const {supabase,user}=await authenticated();const {error}=await supabase.from("detalle_produccion_material").upsert({produccion_id:Number(formData.get("produccion_id")),material_id:Number(formData.get("material_id")),cantidad:Number(formData.get("cantidad")),costo_unitario:Number(formData.get("costo_unitario")),created_by:user.id,updated_by:user.id},{onConflict:"produccion_id,material_id"});if(error)throw new Error(error.message);revalidatePath("/produccion")}
export async function addProductionLabor(formData:FormData){const {supabase,user}=await authenticated();const {error}=await supabase.from("detalle_mano_obra").upsert({produccion_id:Number(formData.get("produccion_id")),trabajador_id:Number(formData.get("trabajador_id")),tipo_pago:String(formData.get("tipo_pago")),cantidad:Number(formData.get("cantidad")),costo_unitario:Number(formData.get("costo_unitario")),created_by:user.id,updated_by:user.id},{onConflict:"produccion_id,trabajador_id"});if(error)throw new Error(error.message);revalidatePath("/produccion")}
export async function finishProduction(formData:FormData){const {supabase,user}=await authenticated();const produccionId=Number(formData.get("produccion_id")),loteId=Number(formData.get("lote_id"));const {error}=await supabase.from("produccion").update({cantidad_enjavada:Number(formData.get("cantidad_enjavada")),cantidad_javas_utilizadas:Number(formData.get("cantidad_javas_utilizadas")),costo_java_unitario:Number(formData.get("costo_java_unitario")),fecha_fin:new Date().toISOString(),estado:"TERMINADA",updated_by:user.id}).eq("id",produccionId);if(error)throw new Error(error.message);await supabase.from("lote").update({estado:"LISTO",updated_by:user.id}).eq("id",loteId);revalidatePath("/produccion")}
export async function createShipment(formData:FormData){const {supabase}=await authenticated();const {error}=await supabase.rpc("crear_envio",{p_lote_id:Number(formData.get("lote_id")),p_cliente_id:Number(formData.get("cliente_id")),p_transportista_id:Number(formData.get("transportista_id")),p_cantidad_javas:Number(formData.get("cantidad_javas")),p_precio_flete_java:Number(formData.get("precio_flete_java")),p_placa_vehiculo:String(formData.get("placa_vehiculo")||"")||null,p_fecha_programada:String(formData.get("fecha_programada")||"")||null});if(error)throw new Error(error.message);revalidatePath("/envios")}
export async function dispatchShipment(formData:FormData){const {supabase,user}=await authenticated();const {error}=await supabase.from("envio").update({estado:"ENVIADO",fecha_envio:new Date().toISOString(),updated_by:user.id}).eq("id",Number(formData.get("id")));if(error)throw new Error(error.message);revalidatePath("/envios")}
export async function updateShipment(formData:FormData){const {supabase,user}=await authenticated();const {error}=await supabase.from("envio").update({cliente_id:Number(formData.get("cliente_id")),transportista_id:Number(formData.get("transportista_id")),cantidad_javas:Number(formData.get("cantidad_javas")),precio_flete_java:Number(formData.get("precio_flete_java")),placa_vehiculo:String(formData.get("placa_vehiculo")||"")||null,fecha_programada:String(formData.get("fecha_programada")||"")||null,updated_by:user.id}).eq("id",Number(formData.get("id"))).eq("estado","PENDIENTE").eq("anulado",false);if(error)throw new Error(error.message);revalidatePath("/envios")}
export async function annulShipment(formData:FormData){const {supabase,user}=await authenticated();const id=Number(formData.get("id"));const {data:reception}=await supabase.from("recepcion").select("id").eq("envio_id",id).maybeSingle();if(reception)throw new Error("No se puede anular un envío que ya tiene recepción");const {error}=await supabase.from("envio").update({anulado:true,updated_by:user.id}).eq("id",id).eq("estado","PENDIENTE");if(error)throw new Error(error.message);revalidatePath("/envios")}
export async function createReception(formData:FormData){const {supabase,user}=await authenticated();const {error}=await supabase.from("recepcion").insert({envio_id:Number(formData.get("envio_id")),cantidad_aceptada:Number(formData.get("cantidad_aceptada")),cantidad_rechazada:Number(formData.get("cantidad_rechazada")),observaciones:String(formData.get("observaciones")||"")||null,created_by:user.id,updated_by:user.id});if(error)throw new Error(error.message);revalidatePath("/recepciones")}
export async function updateReception(formData:FormData){const {supabase,user}=await authenticated();const id=Number(formData.get("id"));const rejected=Number(formData.get("cantidad_rechazada"));const {data:details,error:readError}=await supabase.from("rechazo").select("cantidad").eq("recepcion_id",id);if(readError)throw new Error(readError.message);const detailed=(details||[]).reduce((sum,row)=>sum+Number(row.cantidad),0);if(detailed>rejected)throw new Error(`La recepción ya tiene ${detailed} javas detalladas por motivo`);const {error}=await supabase.from("recepcion").update({cantidad_aceptada:Number(formData.get("cantidad_aceptada")),cantidad_rechazada:rejected,observaciones:String(formData.get("observaciones")||"")||null,updated_by:user.id}).eq("id",id).eq("estado","BORRADOR");if(error)throw new Error(error.message);revalidatePath("/recepciones")}
export async function addReceptionRejection(formData:FormData){const {supabase,user}=await authenticated();const {error}=await supabase.from("rechazo").insert({recepcion_id:Number(formData.get("recepcion_id")),motivo_rechazo_id:Number(formData.get("motivo_rechazo_id")),cantidad:Number(formData.get("cantidad")),observaciones:String(formData.get("observaciones")||"")||null,created_by:user.id,updated_by:user.id});if(error)throw new Error(error.message);revalidatePath("/recepciones")}
export async function confirmReception(formData:FormData){const {supabase}=await authenticated();const {error}=await supabase.rpc("confirmar_recepcion",{p_recepcion_id:Number(formData.get("id"))});if(error)throw new Error(error.message);revalidatePath("/recepciones");revalidatePath("/ventas")}
export async function registerRejectionLoss(formData:FormData){const {supabase}=await authenticated();const {error}=await supabase.rpc("registrar_perdida_rechazo",{p_rechazo_id:Number(formData.get("rechazo_id")),p_cantidad:Number(formData.get("cantidad")),p_observaciones:String(formData.get("observaciones")||"")||null});if(error)throw new Error(error.message);revalidatePath("/recepciones")}
export async function createRecoverySale(formData:FormData){const {supabase}=await authenticated();const {error}=await supabase.rpc("generar_venta_recuperacion",{p_rechazo_id:Number(formData.get("rechazo_id")),p_cliente_id:Number(formData.get("cliente_id")),p_cantidad:Number(formData.get("cantidad")),p_precio_java:Number(formData.get("precio_java")),p_observaciones:String(formData.get("observaciones")||"")||null});if(error)throw new Error(error.message);revalidatePath("/recepciones");revalidatePath("/ventas");revalidatePath("/finanzas")}
export async function createSale(formData:FormData){const {supabase}=await authenticated();const {error}=await supabase.rpc("generar_venta_normal",{p_recepcion_id:Number(formData.get("recepcion_id")),p_precio_java:Number(formData.get("precio_java"))});if(error)throw new Error(error.message);revalidatePath("/ventas")}
export async function annulSale(formData:FormData){const {supabase,user}=await authenticated();const id=Number(formData.get("id"));const {data:payment}=await supabase.from("pago_venta").select("id").eq("venta_id",id).eq("anulado",false).limit(1).maybeSingle();if(payment)throw new Error("Anula primero los cobros registrados para esta venta");const {error}=await supabase.from("venta").update({estado:"ANULADA",updated_by:user.id}).eq("id",id).neq("estado","PAGADA");if(error)throw new Error(error.message);revalidatePath("/ventas");revalidatePath("/finanzas")}
export async function registerExpense(formData:FormData){const {supabase,user}=await authenticated();const {error}=await supabase.from("gasto").insert({categoria_gasto_id:Number(formData.get("categoria_gasto_id")),fecha_gasto:String(formData.get("fecha_gasto")),concepto:String(formData.get("concepto")),monto:Number(formData.get("monto")),medio_pago:String(formData.get("medio_pago")),numero_comprobante:String(formData.get("numero_comprobante")||"")||null,created_by:user.id,updated_by:user.id});if(error)throw new Error(error.message);revalidatePath("/finanzas")}
export async function annulExpense(formData:FormData){const {supabase,user}=await authenticated();const {error}=await supabase.from("gasto").update({anulado:true,updated_by:user.id}).eq("id",Number(formData.get("id")));if(error)throw new Error(error.message);revalidatePath("/finanzas")}
export async function registerSalePayment(formData:FormData){const {supabase,user}=await authenticated();const {error}=await supabase.from("pago_venta").insert({venta_id:Number(formData.get("venta_id")),monto:Number(formData.get("monto")),medio_pago:String(formData.get("medio_pago")),numero_operacion:String(formData.get("numero_operacion")||"")||null,created_by:user.id,updated_by:user.id});if(error)throw new Error(error.message);revalidatePath("/finanzas");revalidatePath("/ventas")}
export async function annulSalePayment(formData:FormData){const {supabase,user}=await authenticated();const {error}=await supabase.from("pago_venta").update({anulado:true,updated_by:user.id}).eq("id",Number(formData.get("id")));if(error)throw new Error(error.message);revalidatePath("/finanzas");revalidatePath("/ventas")}
export async function setProducerPrice(formData:FormData){const {supabase}=await authenticated();const {error}=await supabase.rpc("determinar_precio_productor",{p_lote_id:Number(formData.get("lote_id")),p_precio_java:Number(formData.get("precio_java"))});if(error)throw new Error(error.message);revalidatePath("/finanzas");revalidatePath("/produccion")}
export async function registerProducerPayment(formData:FormData){const {supabase,user}=await authenticated();const {error}=await supabase.from("pago_productor").insert({lote_id:Number(formData.get("lote_id")),monto:Number(formData.get("monto")),medio_pago:String(formData.get("medio_pago")),numero_operacion:String(formData.get("numero_operacion")||"")||null,observaciones:String(formData.get("observaciones")||"")||null,created_by:user.id,updated_by:user.id});if(error)throw new Error(error.message);revalidatePath("/finanzas")}

