"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
const allowed=new Set(["productor","cliente","trabajador","transportista","material","producto","variedad","motivo_rechazo","categoria_gasto"]);const pathFor:Record<string,string>={productor:"/productores",cliente:"/clientes",trabajador:"/trabajadores",transportista:"/transportistas",material:"/materiales",producto:"/productos",variedad:"/variedades",motivo_rechazo:"/motivos-rechazo",categoria_gasto:"/categorias-gasto"};
async function authenticated(){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Sesión requerida");return {supabase,user}}
export async function saveMaster(formData:FormData){const table=String(formData.get("table"));if(!allowed.has(table))throw new Error("Tabla no permitida");const {supabase,user}=await authenticated();const payload:Record<string,string|number|null>={nombre:String(formData.get("nombre")||"").trim(),updated_by:user.id};if(["productor","cliente","trabajador","transportista"].includes(table)){payload.numero_documento=String(formData.get("numero_documento")||"").trim()||null;payload.telefono=String(formData.get("telefono")||"").trim()||null}if(["producto","variedad","motivo_rechazo","categoria_gasto"].includes(table))payload.descripcion=String(formData.get("descripcion")||"").trim()||null;if(table==="material"){payload.unidad_medida=String(formData.get("unidad_medida")||"").trim();const cost=String(formData.get("costo_referencia")||"");payload.costo_referencia=cost?Number(cost):null}if(table==="variedad")payload.producto_id=Number(formData.get("producto_id"));const id=String(formData.get("id")||"");const result=id?await supabase.from(table).update(payload).eq("id",id):await supabase.from(table).insert({...payload,created_by:user.id});if(result.error)throw new Error(result.error.message);revalidatePath(pathFor[table])}
export async function toggleMaster(formData:FormData){const table=String(formData.get("table"));if(!allowed.has(table))throw new Error("Tabla no permitida");const {supabase,user}=await authenticated();const {error}=await supabase.from(table).update({activo:String(formData.get("activo"))!=="true",updated_by:user.id}).eq("id",String(formData.get("id")));if(error)throw new Error(error.message);revalidatePath(pathFor[table])}
export async function logout(){const supabase=await createClient();await supabase.auth.signOut();redirect("/login")}
export async function createLot(formData:FormData){const {supabase,user}=await authenticated();const estimated=String(formData.get("cantidad_estimada_javas")||"");const {error}=await supabase.from("lote").insert({productor_id:Number(formData.get("productor_id")),variedad_id:Number(formData.get("variedad_id")),fecha_registro:String(formData.get("fecha_registro")),cantidad_estimada_javas:estimated?Number(estimated):null,observaciones:String(formData.get("observaciones")||"").trim()||null,created_by:user.id,updated_by:user.id});if(error)throw new Error(error.message);revalidatePath("/produccion")}
export async function startProduction(formData:FormData){const {supabase,user}=await authenticated();const loteId=Number(formData.get("lote_id"));const {error}=await supabase.from("produccion").insert({lote_id:loteId,created_by:user.id,updated_by:user.id});if(error)throw new Error(error.message);await supabase.from("lote").update({estado:"EN_PRODUCCION",updated_by:user.id}).eq("id",loteId);revalidatePath("/produccion")}
export async function addProductionMaterial(formData:FormData){const {supabase,user}=await authenticated();const {error}=await supabase.from("detalle_produccion_material").upsert({produccion_id:Number(formData.get("produccion_id")),material_id:Number(formData.get("material_id")),cantidad:Number(formData.get("cantidad")),costo_unitario:Number(formData.get("costo_unitario")),created_by:user.id,updated_by:user.id},{onConflict:"produccion_id,material_id"});if(error)throw new Error(error.message);revalidatePath("/produccion")}
export async function addProductionLabor(formData:FormData){const {supabase,user}=await authenticated();const {error}=await supabase.from("detalle_mano_obra").upsert({produccion_id:Number(formData.get("produccion_id")),trabajador_id:Number(formData.get("trabajador_id")),tipo_pago:String(formData.get("tipo_pago")),cantidad:Number(formData.get("cantidad")),costo_unitario:Number(formData.get("costo_unitario")),created_by:user.id,updated_by:user.id},{onConflict:"produccion_id,trabajador_id"});if(error)throw new Error(error.message);revalidatePath("/produccion")}
export async function finishProduction(formData:FormData){const {supabase,user}=await authenticated();const produccionId=Number(formData.get("produccion_id")),loteId=Number(formData.get("lote_id"));const {error}=await supabase.from("produccion").update({cantidad_enjavada:Number(formData.get("cantidad_enjavada")),cantidad_javas_utilizadas:Number(formData.get("cantidad_javas_utilizadas")),costo_java_unitario:Number(formData.get("costo_java_unitario")),fecha_fin:new Date().toISOString(),estado:"TERMINADA",updated_by:user.id}).eq("id",produccionId);if(error)throw new Error(error.message);await supabase.from("lote").update({estado:"LISTO",updated_by:user.id}).eq("id",loteId);revalidatePath("/produccion")}

