import { annulExpense, annulSalePayment, registerExpense, registerSalePayment } from "@/app/actions";
import { ProducerFinance } from "@/components/producer-finance";
type Choice={id:number;nombre?:string;codigo?:string};type Row=Record<string,unknown>;
const money=(v:unknown)=>`S/ ${Number(v||0).toFixed(2)}`;const methods=<><option>EFECTIVO</option><option>TRANSFERENCIA</option><option>YAPE</option><option>PLIN</option><option>OTRO</option></>;
export function FinanceDashboard({rows,choices}:{rows:Row[];choices:Record<string,Choice[]>}){const balances=rows.filter(r=>r.kind==="producerBalance");const profits=rows.filter(r=>r.kind==="profit");return <><div className="financeGrid"><FinancePanel title="Registrar gasto"><form action={registerExpense} className="operationForm"><Select name="categoria_gasto_id" label="Categoría" items={choices.categories||[]}/><label>Fecha<input name="fecha_gasto" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></label><label>Concepto<input name="concepto" required/></label><label>Monto<input name="monto" type="number" min=".01" step=".01" required/></label><label>Medio de pago<select name="medio_pago">{methods}</select></label><button className="primary">Registrar gasto</button></form><Records rows={rows.filter(r=>r.kind==="expense")} render={r=><><strong>{String(r.concepto)}</strong><span>{String(r.fecha_gasto)} · {money(r.monto)}</span></>}/></FinancePanel><FinancePanel title="Registrar cobro"><form action={registerSalePayment} className="operationForm"><Select name="venta_id" label="Venta pendiente" items={choices.sales||[]}/><label>Monto<input name="monto" type="number" min=".01" step=".01" required/></label><label>Medio de pago<select name="medio_pago">{methods}</select></label><label>Número de operación<input name="numero_operacion"/></label><button className="primary">Registrar cobro</button></form><Records rows={rows.filter(r=>r.kind==="balance")} render={r=><><strong>{String(r.codigo)}</strong><span>Saldo {money(r.saldo_pendiente)}</span></>}/></FinancePanel></div><ProducerFinance withoutPrice={(choices.withoutPrice||[]) as {id:number;codigo:string}[]} balances={balances} profitability={profits}/></>}
function FinancePanel({title,children}:{title:string;children:React.ReactNode}){return <section className="panel operationCreate"><h2>{title}</h2>{children}</section>}
function Select({name,label,items}:{name:string;label:string;items:Choice[]}){return <label>{label}<select name={name} required defaultValue=""><option value="" disabled>Seleccionar</option>{items.map(x=><option key={x.id} value={x.id}>{x.codigo||x.nombre}</option>)}</select></label>}
function Records({rows,render}:{rows:Row[];render:(r:Row)=>React.ReactNode}){return rows.length?<div className="compactRecords">{rows.slice(0,6).map((r,i)=><div key={String(r.id||r.codigo||i)}><span className="recordData">{render(r)}</span>{r.kind==="expense"?<form action={annulExpense}><input type="hidden" name="id" value={String(r.id)}/><button className="miniDanger">Anular</button></form>:r.kind==="payment"?<form action={annulSalePayment}><input type="hidden" name="id" value={String(r.id)}/><button className="miniDanger">Anular</button></form>:null}</div>)}</div>:null}

