import { addProductionLabor, addProductionMaterial, archiveLot, createLot, finishProduction, startProduction, updateLot } from "@/app/actions";

type Choice={id:number;nombre:string};
type Variety=Choice&{producto:{nombre:string}|null};
type MaterialDetail={material_id:number;cantidad:number;costo_unitario:number;costo_total:number;material:{nombre:string;unidad_medida:string}|null};
type LaborDetail={trabajador_id:number;tipo_pago:string;cantidad:number;costo_unitario:number;costo_total:number;trabajador:{nombre:string}|null};
type Production={id:number;estado:string;cantidad_enjavada:number|null;costo_total_javas:number|null;detalle_produccion_material:MaterialDetail[];detalle_mano_obra:LaborDetail[]};
type Lot={id:number;codigo:string;fecha_registro:string;cantidad_estimada_javas:number|null;estado:string;productor:{nombre:string}|null;variedad:Variety|null;produccion:Production|Production[]|null};
const money=(value:number|null|undefined)=>`S/ ${Number(value||0).toFixed(2)}`;

export function LotsManager({lots,producers,varieties,materials,workers}:{lots:Lot[];producers:Choice[];varieties:Variety[];materials:Choice[];workers:Choice[]}){return <div className="productionPage"><div className="masterLayout lotLayout">
  <section className="panel formPanel"><h2>Registrar lote</h2><form action={createLot} className="masterForm">
    <label>Productor<select name="productor_id" required defaultValue=""><option value="" disabled>Seleccionar productor</option>{producers.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select></label>
    <label>Producto y variedad<select name="variedad_id" required defaultValue=""><option value="" disabled>Seleccionar variedad</option>{varieties.map(x=><option key={x.id} value={x.id}>{x.producto?.nombre} — {x.nombre}</option>)}</select></label>
    <label>Fecha<input name="fecha_registro" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></label><label>Javas estimadas<input name="cantidad_estimada_javas" type="number" min="1"/></label><label>Observaciones<textarea name="observaciones" rows={3}/></label><button className="primary">Crear lote</button>
  </form></section>
  <section className="lotCards">{lots.map(l=><LotCard key={l.id} lot={l} producers={producers} varieties={varieties} materials={materials} workers={workers}/>)}</section>
</div></div>}

function LotCard({lot,producers,varieties,materials,workers}:{lot:Lot;producers:Choice[];varieties:Variety[];materials:Choice[];workers:Choice[]}){
  const production=Array.isArray(lot.produccion)?lot.produccion[0]:lot.produccion;
  const materialRows=production?.detalle_produccion_material||[];const laborRows=production?.detalle_mano_obra||[];
  const materialCost=materialRows.reduce((a,x)=>a+Number(x.costo_total),0);const laborCost=laborRows.reduce((a,x)=>a+Number(x.costo_total),0);const finished=production?.estado==="TERMINADA";
  return <article className="panel lotCard"><div className="lotHead"><div><p className="eyebrow">{lot.codigo}</p><h2>{lot.variedad?.producto?.nombre} — {lot.variedad?.nombre}</h2><p>{lot.productor?.nombre} · {lot.fecha_registro} · {lot.cantidad_estimada_javas||"—"} javas estimadas</p></div><span className="status">{lot.estado.replaceAll("_"," ")}</span></div>
  {lot.estado==="RECIBIDO"&&<div className="lotEdit"><div><h3>Corregir datos del lote</h3><p>Disponible mientras la producción no haya iniciado.</p></div><form action={updateLot} className="lotEditForm"><input type="hidden" name="id" value={lot.id}/><select name="productor_id" defaultValue={producers.find(x=>x.nombre===lot.productor?.nombre)?.id} aria-label="Productor">{producers.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select><select name="variedad_id" defaultValue={varieties.find(x=>x.nombre===lot.variedad?.nombre&&x.producto?.nombre===lot.variedad?.producto?.nombre)?.id} aria-label="Variedad">{varieties.map(x=><option key={x.id} value={x.id}>{x.producto?.nombre} — {x.nombre}</option>)}</select><input name="fecha_registro" type="date" defaultValue={lot.fecha_registro}/><input name="cantidad_estimada_javas" type="number" min="1" defaultValue={lot.cantidad_estimada_javas||undefined} placeholder="Javas"/><input name="observaciones" placeholder="Observaciones"/><button className="secondary">Guardar cambios</button></form><form action={archiveLot}><input type="hidden" name="id" value={lot.id}/><button className="danger">Eliminar lote</button></form></div>}
  {!production?<form action={startProduction} className="lotAction"><input type="hidden" name="lote_id" value={lot.id}/><button className="primary">Iniciar producción</button></form>:<>
    <div className="productionSummary"><span>Materiales <strong>{money(materialCost)}</strong></span><span>Mano de obra <strong>{money(laborCost)}</strong></span><span>Enjavadas <strong>{production.cantidad_enjavada??"—"}</strong></span><span>Javas <strong>{money(production.costo_total_javas)}</strong></span></div>
    <div className="productionWorkspace">
      <section className="productionSection"><SectionTitle title="Materiales usados" total={materialCost}/>{materialRows.length?<div className="resourceTableWrap"><table className="resourceTable"><thead><tr><th>Material</th><th>Cantidad</th><th>Costo unit.</th><th>Total</th></tr></thead><tbody>{materialRows.map(row=><tr key={row.material_id}><td><strong>{row.material?.nombre||"Material"}</strong></td><td>{row.cantidad} {row.material?.unidad_medida||""}</td><td>{money(row.costo_unitario)}</td><td>{money(row.costo_total)}</td></tr>)}</tbody></table></div>:<p className="resourceEmpty">Aún no has registrado materiales en este lote.</p>}
      {!finished&&<><p className="formHint">Si eliges nuevamente el mismo material, se actualizarán su cantidad y costo; no se duplicará.</p><form action={addProductionMaterial} className="resourceForm"><input type="hidden" name="produccion_id" value={production.id}/><FieldSelect label="Material" name="material_id" choices={materials}/><FieldNumber label="Cantidad" name="cantidad" step="0.001"/><FieldNumber label="Costo unitario" name="costo_unitario" step="0.0001"/><button className="secondary">Agregar o actualizar</button></form></>}</section>
      <section className="productionSection"><SectionTitle title="Mano de obra" total={laborCost}/>{laborRows.length?<div className="resourceTableWrap"><table className="resourceTable"><thead><tr><th>Trabajador</th><th>Pago</th><th>Cantidad</th><th>Total</th></tr></thead><tbody>{laborRows.map(row=><tr key={row.trabajador_id}><td><strong>{row.trabajador?.nombre||"Trabajador"}</strong></td><td>{row.tipo_pago}</td><td>{row.cantidad} × {money(row.costo_unitario)}</td><td>{money(row.costo_total)}</td></tr>)}</tbody></table></div>:<p className="resourceEmpty">Aún no has registrado trabajadores en este lote.</p>}
      {!finished&&<form action={addProductionLabor} className="resourceForm laborForm"><input type="hidden" name="produccion_id" value={production.id}/><FieldSelect label="Trabajador" name="trabajador_id" choices={workers}/><label>Tipo de pago<select name="tipo_pago" required defaultValue="JORNADA"><option>JORNADA</option><option>JAVA</option><option>DIA</option><option>OTRO</option></select></label><FieldNumber label="Cantidad" name="cantidad" step="0.001"/><FieldNumber label="Costo unitario" name="costo_unitario" step="0.0001"/><button className="secondary">Agregar o actualizar</button></form>}</section>
      {!finished&&<section className="finishSection"><div><h3>Finalizar producción</h3><p>Confirma el resultado cuando todos los materiales y trabajadores estén registrados.</p></div><form action={finishProduction} className="finishForm"><input type="hidden" name="produccion_id" value={production.id}/><input type="hidden" name="lote_id" value={lot.id}/><FieldNumber label="Cantidad enjavada" name="cantidad_enjavada" step="1" min="1"/><FieldNumber label="Javas utilizadas" name="cantidad_javas_utilizadas" step="1" min="1"/><FieldNumber label="Costo por java" name="costo_java_unitario" step="0.0001"/><button className="primary">Finalizar producción</button></form></section>}
    </div></>}
  </article>;
}
function SectionTitle({title,total}:{title:string;total:number}){return <div className="sectionTitle"><div><h3>{title}</h3><p>Detalle guardado en este lote</p></div><strong>{money(total)}</strong></div>}
function FieldSelect({label,name,choices}:{label:string;name:string;choices:Choice[]}){return <label>{label}<select name={name} required defaultValue=""><option value="" disabled>Seleccionar {label.toLowerCase()}</option>{choices.map(x=><option key={x.id} value={x.id}>{x.nombre}</option>)}</select></label>}
function FieldNumber({label,name,step,min="0"}:{label:string;name:string;step:string;min?:string}){return <label>{label}<input name={name} type="number" min={min} step={step} placeholder="0" required/></label>}

