import { saveMaster, toggleMaster } from "@/app/actions";
type Row={id:number;nombre:string;numero_documento?:string|null;telefono?:string|null;unidad_medida?:string|null;costo_referencia?:number|null;descripcion?:string|null;activo:boolean;producto?:{nombre:string}|null};
type Product={id:number;nombre:string};
export function MasterManager({table,title,rows,products=[]}:{table:string;title:string;rows:Row[];products?:Product[]}){
  const material=table==="material", variety=table==="variedad", descriptive=["producto","motivo_rechazo","categoria_gasto","variedad"].includes(table);
  const col2=material?"Unidad":variety?"Producto":descriptive?"Descripción":"Documento";
  return <div className="masterLayout"><section className="panel formPanel"><h2>Nuevo registro</h2><form action={saveMaster} className="masterForm"><input type="hidden" name="table" value={table}/>{variety?<label>Producto<select name="producto_id" required defaultValue=""><option value="" disabled>Seleccionar producto</option>{products.map(p=><option key={p.id} value={p.id}>{p.nombre}</option>)}</select></label>:null}<label>Nombre<input name="nombre" required maxLength={150}/></label>{material?<><label>Unidad de medida<input name="unidad_medida" required maxLength={20}/></label><label>Costo de referencia<input name="costo_referencia" type="number" min="0" step="0.0001"/></label></>:descriptive?<label>Descripción<input name="descripcion" maxLength={250}/></label>:<><label>Documento<input name="numero_documento" maxLength={20}/></label><label>Teléfono<input name="telefono" maxLength={20}/></label></>}<button className="primary" type="submit">Guardar</button></form></section><section className="panel"><div className="panelHead"><div><h2>Listado de {title.toLowerCase()}</h2><p>{rows.length} registros</p></div></div><div className="tableWrap"><table><thead><tr><th>Nombre</th><th>{col2}</th>{!descriptive&&!material?<th>Teléfono</th>:null}<th>Estado</th><th></th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td>{row.nombre}</td><td>{material?row.unidad_medida:variety?row.producto?.nombre||"—":descriptive?row.descripcion||"—":row.numero_documento||"—"}</td>{!descriptive&&!material?<td>{row.telefono||"—"}</td>:null}<td><span className={`status ${row.activo?"":"off"}`}>{row.activo?"Activo":"Inactivo"}</span></td><td><form action={toggleMaster}><input type="hidden" name="table" value={table}/><input type="hidden" name="id" value={row.id}/><input type="hidden" name="activo" value={String(row.activo)}/><button className="secondary" type="submit">{row.activo?"Desactivar":"Activar"}</button></form></td></tr>)}</tbody></table></div></section></div>
}

