import { addReceptionRejection, annulSale, annulShipment, confirmReception, createReception, createRecoverySale, createSale, createShipment, dispatchShipment, registerExpense, registerProducerPayment, registerRejectionLoss, registerSalePayment, setProducerPrice, updateReception, updateShipment } from "@/app/actions";
import { FinanceDashboard } from "@/components/finance-dashboard";
import { SaleCard, ShipmentCard } from "@/components/correction-cards";
import { ReceptionCorrection } from "@/components/reception-correction";
import { PaymentHistory } from "@/components/payment-history";
type Choice={id:number;nombre?:string;codigo?:string};
type Row=Record<string,unknown>;
const money=(v:unknown)=>`S/ ${Number(v||0).toFixed(2)}`;
const payMethods=<><option>EFECTIVO</option><option>TRANSFERENCIA</option><option>YAPE</option><option>PLIN</option><option>OTRO</option></>;
function ChoiceField({name,label,items}:{name:string;label:string;items:Choice[]}){return <label>{label}<select name={name} required defaultValue=""><option value="" disabled>Seleccionar</option>{items.map(x=><option key={x.id} value={x.id}>{x.codigo||x.nombre}</option>)}</select></label>}
export function OperationsManager({module,rows,choices}:{module:string;rows:Row[];choices:Record<string,Choice[]>}){
 if(module==="envios")return <Module title="Nuevo envío" form={<form action={createShipment} className="operationForm"><ChoiceField name="lote_id" label="Lote listo" items={choices.lots||[]}/><ChoiceField name="cliente_id" label="Cliente" items={choices.clients||[]}/><ChoiceField name="transportista_id" label="Transportista" items={choices.carriers||[]}/><label>Javas<input name="cantidad_javas" type="number" min="1" required/></label><label>Flete por java<input name="precio_flete_java" type="number" min="0" step=".0001" required/></label><label>Placa<input name="placa_vehiculo"/></label><label>Fecha programada<input name="fecha_programada" type="date"/></label><button className="primary">Crear envío</button></form>}><Cards rows={rows} render={r=><ShipmentCard row={r} clients={choices.clients||[]} carriers={choices.carriers||[]}/>} /></Module>;
 if(module==="recepciones")return <Module title="Registrar recepción" form={<form action={createReception} className="operationForm"><ChoiceField name="envio_id" label="Envío pendiente" items={choices.shipments||[]}/><label>Javas aceptadas<input name="cantidad_aceptada" type="number" min="0" required/></label><label>Javas rechazadas<input name="cantidad_rechazada" type="number" min="0" required/></label><label>Observaciones<input name="observaciones"/></label><button className="primary">Guardar recepción</button></form>}><Cards rows={rows} render={r=><><ReceptionCard row={r} reasons={choices.reasons||[]} clients={choices.clients||[]}/><ReceptionCorrection row={r}/></>} /></Module>;
 if(module==="ventas")return <Module title="Registrar venta" form={<form action={createSale} className="operationForm"><ChoiceField name="recepcion_id" label="Recepción confirmada" items={choices.receptions||[]}/><label>Precio por java<input name="precio_java" type="number" min="0" step=".0001" required/></label><button className="primary">Generar venta</button></form>}><Cards rows={rows} render={r=><SaleCard row={r}/>} /></Module>;
 if(module==="finanzas")return <><FinanceDashboard rows={rows} choices={choices}/><PaymentHistory rows={rows}/></>;
 if(module==="finanzas")return <div className="financeGrid"><Module title="Registrar gasto" form={<form action={registerExpense} className="operationForm"><ChoiceField name="categoria_gasto_id" label="Categoría" items={choices.categories||[]}/><label>Fecha<input name="fecha_gasto" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></label><label>Concepto<input name="concepto" required/></label><label>Monto<input name="monto" type="number" min=".01" step=".01" required/></label><label>Medio de pago<select name="medio_pago">{payMethods}</select></label><label>Comprobante<input name="numero_comprobante"/></label><button className="primary">Registrar gasto</button></form>}><Cards rows={rows.filter(r=>r.kind==="expense")} render={r=><><CardHead code={r.concepto}/><p>{String(r.fecha_gasto)} · {String((r.categoria_gasto as Row)?.nombre||"")}</p><strong>{money(r.monto)}</strong></>}/></Module><Module title="Registrar cobro" form={<form action={registerSalePayment} className="operationForm"><ChoiceField name="venta_id" label="Venta pendiente" items={choices.sales||[]}/><label>Monto<input name="monto" type="number" min=".01" step=".01" required/></label><label>Medio de pago<select name="medio_pago">{payMethods}</select></label><label>Número de operación<input name="numero_operacion"/></label><button className="primary">Registrar cobro</button></form>}><Cards rows={rows.filter(r=>r.kind==="balance")} render={r=><><CardHead code={r.codigo}/><p>Total {money(r.monto_total)} · Pagado {money(r.monto_pagado)}</p><strong>Saldo {money(r.saldo_pendiente)}</strong></>}/></Module></div>;
 return null;
}
function Module({title,form,children}:{title:string;form:React.ReactNode;children:React.ReactNode}){return <section className="operationModule"><div className="panel operationCreate"><h2>{title}</h2>{form}</div><div className="operationCards">{children}</div></section>}
function Cards({rows,render}:{rows:Row[];render:(row:Row)=>React.ReactNode}){return rows.length?rows.map((r,i)=><article className="panel operationCard" key={String(r.id||r.codigo||i)}>{render(r)}</article>):<div className="panel empty">Todavía no hay registros.</div>}
function CardHead({code,state}:{code:unknown;state?:unknown}){return <div className="cardHead"><h2>{String(code||"")}</h2>{state?<span className="status">{String(state).replaceAll("_"," ")}</span>:null}</div>}
function ReceptionCard({row,reasons,clients}:{row:Row;reasons:Choice[];clients:Choice[]}){const rejects=(row.rechazo||[]) as Row[];const declared=Number(row.cantidad_rechazada||0);const detailed=rejects.reduce((sum,item)=>sum+Number(item.cantidad||0),0);const complete=declared===detailed;return <><CardHead code={(row.envio as Row)?.codigo} state={row.estado}/><p>Aceptadas: {String(row.cantidad_aceptada)} · Rechazadas: {declared}</p>{rejects.length?<div className="rejectionDetails">{rejects.map((item,index)=><RejectionDisposition key={String(item.id||index)} item={item} confirmed={row.estado==="CONFIRMADA"} clients={clients}/>)}</div>:null}{row.estado==="BORRADOR"&&declared>0&&!complete?<><p className="validationNotice">Falta detallar {declared-detailed} java(s) rechazadas para poder confirmar.</p><form action={addReceptionRejection} className="rejectionForm"><input type="hidden" name="recepcion_id" value={String(row.id)}/><ChoiceField name="motivo_rechazo_id" label="Motivo" items={reasons}/><label>Cantidad<input name="cantidad" type="number" min="1" max={declared-detailed} required/></label><label>Observaciones<input name="observaciones"/></label><button className="secondary">Agregar motivo</button></form></>:null}{row.estado==="BORRADOR"&&complete?<form action={confirmReception}><input type="hidden" name="id" value={String(row.id)}/><button className="primary">Confirmar recepción</button></form>:null}</>}
function RejectionDisposition({item,confirmed,clients}:{item:Row;confirmed:boolean;clients:Choice[]}){const dispositions=(item.disposicion_rechazo||[]) as Row[];const disposed=dispositions.filter(x=>x.estado==="PERDIDA"||x.estado==="VENDIDA").reduce((sum,x)=>sum+Number(x.cantidad||0),0);const remaining=Number(item.cantidad||0)-disposed;return <div className="rejectionItem"><div><strong>{String((item.motivo_rechazo as Row)?.nombre||"Motivo")}</strong><span>{String(item.cantidad)} javas · {remaining>0?`${remaining} pendientes`:"Resuelto"}</span></div>{confirmed&&remaining>0?<div className="dispositionForms"><form action={registerRejectionLoss}><input type="hidden" name="rechazo_id" value={String(item.id)}/><input name="cantidad" type="number" min="1" max={remaining} defaultValue={remaining}/><input name="observaciones" placeholder="Observaciones"/><button className="secondary">Registrar pérdida</button></form><form action={createRecoverySale}><input type="hidden" name="rechazo_id" value={String(item.id)}/><ChoiceField name="cliente_id" label="Cliente comprador" items={clients}/><input name="cantidad" type="number" min="1" max={remaining} defaultValue={remaining} aria-label="Cantidad"/><input name="precio_java" type="number" min="0" step=".0001" placeholder="Precio por java" required/><button className="primary">Venta de recuperación</button></form></div>:null}</div>}

