import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowRight, Boxes, CircleDollarSign, ClipboardCheck, PackageOpen, Sprout, Truck, Users } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { MasterManager } from "@/components/master-manager";
import { MasterTabs } from "@/components/master-tabs";
import { LotsManager } from "@/components/lots-manager";
import { createClient } from "@/lib/supabase/server";

const names:Record<string,string>={inicio:"Inicio",produccion:"Producción",envios:"Envíos",recepciones:"Recepciones",ventas:"Ventas",finanzas:"Finanzas",maestros:"Maestros",administracion:"Administración",productores:"Productores",clientes:"Clientes",trabajadores:"Trabajadores",transportistas:"Transportistas",materiales:"Materiales",productos:"Productos",variedades:"Variedades","motivos-rechazo":"Motivos de rechazo","categorias-gasto":"Categorías de gasto"};
const masters=[{n:"Productores",h:"/productores",i:Sprout},{n:"Clientes",h:"/clientes",i:Users},{n:"Trabajadores",h:"/trabajadores",i:Users},{n:"Transportistas",h:"/transportistas",i:Truck},{n:"Materiales",h:"/materiales",i:PackageOpen},{n:"Productos",h:"/productos",i:PackageOpen},{n:"Variedades",h:"/variedades",i:Sprout},{n:"Motivos de rechazo",h:"/motivos-rechazo",i:ClipboardCheck},{n:"Categorías de gasto",h:"/categorias-gasto",i:CircleDollarSign}];
const tableFor:Record<string,string>={productores:"productor",clientes:"cliente",trabajadores:"trabajador",transportistas:"transportista",materiales:"material",productos:"producto",variedades:"variedad","motivos-rechazo":"motivo_rechazo","categorias-gasto":"categoria_gasto"};

export default async function Page({params}:{params:Promise<{section?:string[]}>}){
  const {section=["inicio"]}=await params;const slug=section[0]||"inicio";const title=names[slug]||"Inicio";
  const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");
  const table=tableFor[slug];let rows:Record<string,unknown>[]=[];if(table==="variedad"){const {data}=await supabase.from("variedad").select("*, producto(nombre)").order("nombre");rows=(data||[]) as unknown as Record<string,unknown>[]}else if(table){const {data}=await supabase.from(table).select("*").order("nombre");rows=(data||[]) as unknown as Record<string,unknown>[]}let products:{id:number;nombre:string}[]=[];if(table==="variedad"){const {data}=await supabase.from("producto").select("id,nombre").eq("activo",true).order("nombre");products=data||[]}
  let lotData:{lots:never[];producers:never[];varieties:never[];materials:never[];workers:never[]}={lots:[],producers:[],varieties:[],materials:[],workers:[]};if(slug==="produccion"){const [lots,producers,varieties,materials,workers]=await Promise.all([supabase.from("lote").select("id,codigo,fecha_registro,cantidad_estimada_javas,estado,productor(nombre),variedad(nombre,producto(nombre)),produccion(id,estado,cantidad_enjavada,costo_total_javas,detalle_produccion_material(material_id,cantidad,costo_unitario,costo_total,material(nombre,unidad_medida)),detalle_mano_obra(trabajador_id,tipo_pago,cantidad,costo_unitario,costo_total,trabajador(nombre)))").order("fecha_registro",{ascending:false}),supabase.from("productor").select("id,nombre").eq("activo",true).order("nombre"),supabase.from("variedad").select("id,nombre,producto(nombre)").eq("activo",true).order("nombre"),supabase.from("material").select("id,nombre").eq("activo",true).order("nombre"),supabase.from("trabajador").select("id,nombre").eq("activo",true).order("nombre")]);lotData={lots:(lots.data||[]) as never[],producers:(producers.data||[]) as never[],varieties:(varieties.data||[]) as never[],materials:(materials.data||[]) as never[],workers:(workers.data||[]) as never[]}}
  const inMasters=slug==="maestros"||Boolean(table);
  return <AppShell><header><div><p className="eyebrow">ERP Familia</p><h1>{title}</h1><p className="muted">Control simple y conectado de la operación frutícola.</p></div></header>{inMasters?<MasterTabs/>:null}{slug==="inicio"?<Dashboard/>:slug==="produccion"?<LotsManager {...lotData}/>:slug==="maestros"?<section className="masterGrid">{masters.map(({n,h,i:Icon})=><Link href={h} className="masterCard" key={h}><span><Icon/></span><div><h2>{n}</h2><p>Gestionar registros de {n.toLowerCase()}.</p></div><ArrowRight size={18}/></Link>)}</section>:table?<MasterManager table={table} title={title} rows={rows as never[]} products={products}/>:<section className="panel"><div className="panelHead"><div><h2>{title}</h2><p>Módulo preparado para la siguiente iteración.</p></div></div></section>}</AppShell>
}
function Dashboard(){const cards=[{l:"Lotes activos",v:"—",i:Sprout},{l:"Envíos en tránsito",v:"—",i:Truck},{l:"Recepciones pendientes",v:"—",i:ClipboardCheck},{l:"Ventas del mes",v:"—",i:CircleDollarSign}];return <><section className="stats">{cards.map(({l,v,i:Icon})=><article key={l}><span><Icon/></span><div><p>{l}</p><strong>{v}</strong></div></article>)}</section><section className="panel flow"><Boxes/><div><h2>LOTE → ENVÍO → RECEPCIÓN → VENTA</h2><p>La columna vertebral operativa ya está reflejada en el esquema.</p></div></section></>}

