// @ts-nocheck
import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowRight, Boxes, CircleDollarSign, ClipboardCheck, PackageOpen, Sprout, Truck, Users } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { MasterManager } from "@/components/master-manager";
import { MasterTabs } from "@/components/master-tabs";
import { LotsManager } from "@/components/lots-manager";
import { OperationsManager } from "@/components/operations-manager";
import { createClient } from "@/lib/supabase/server";

const names:Record<string,string>={inicio:"Inicio",produccion:"Producción",envios:"Envíos",recepciones:"Recepciones",ventas:"Ventas",finanzas:"Finanzas",maestros:"Maestros",administracion:"Administración",productores:"Productores",clientes:"Clientes",trabajadores:"Trabajadores",transportistas:"Transportistas",materiales:"Materiales",productos:"Productos",variedades:"Variedades","motivos-rechazo":"Motivos de rechazo","categorias-gasto":"Categorías de gasto"};
const masters=[{n:"Productores",h:"/productores",i:Sprout},{n:"Clientes",h:"/clientes",i:Users},{n:"Trabajadores",h:"/trabajadores",i:Users},{n:"Transportistas",h:"/transportistas",i:Truck},{n:"Materiales",h:"/materiales",i:PackageOpen},{n:"Productos",h:"/productos",i:PackageOpen},{n:"Variedades",h:"/variedades",i:Sprout},{n:"Motivos de rechazo",h:"/motivos-rechazo",i:ClipboardCheck},{n:"Categorías de gasto",h:"/categorias-gasto",i:CircleDollarSign}];
const tableFor:Record<string,string>={productores:"productor",clientes:"cliente",trabajadores:"trabajador",transportistas:"transportista",materiales:"material",productos:"producto",variedades:"variedad","motivos-rechazo":"motivo_rechazo","categorias-gasto":"categoria_gasto"};

export default async function Page({params}:{params:Promise<{section?:string[]}>}){
  const {section=["inicio"]}=await params;const slug=section[0]||"inicio";const title=names[slug]||"Inicio";
  const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");
  const table=tableFor[slug];let rows:Record<string,unknown>[]=[];if(table==="variedad"){const {data}=await supabase.from("variedad").select("*, producto(nombre)").order("nombre");rows=(data||[]) as unknown as Record<string,unknown>[]}else if(table){const {data}=await supabase.from(table).select("*").order("nombre");rows=(data||[]) as unknown as Record<string,unknown>[]}let products:{id:number;nombre:string}[]=[];if(table==="variedad"){const {data}=await supabase.from("producto").select("id,nombre").eq("activo",true).order("nombre");products=data||[]}
  let lotData:{lots:never[];producers:never[];varieties:never[];materials:never[];workers:never[]}={lots:[],producers:[],varieties:[],materials:[],workers:[]};if(slug==="produccion"){const [lots,producers,varieties,materials,workers]=await Promise.all([supabase.from("lote").select("id,codigo,fecha_registro,cantidad_estimada_javas,estado,productor(nombre),variedad(nombre,producto(nombre)),produccion(id,estado,cantidad_enjavada,costo_total_javas,detalle_produccion_material(material_id,cantidad,costo_unitario,costo_total,material(nombre,unidad_medida)),detalle_mano_obra(trabajador_id,tipo_pago,cantidad,costo_unitario,costo_total,trabajador(nombre)))").order("fecha_registro",{ascending:false}),supabase.from("productor").select("id,nombre").eq("activo",true).order("nombre"),supabase.from("variedad").select("id,nombre,producto(nombre)").eq("activo",true).order("nombre"),supabase.from("material").select("id,nombre").eq("activo",true).order("nombre"),supabase.from("trabajador").select("id,nombre").eq("activo",true).order("nombre")]);lotData={lots:(lots.data||[]) as never[],producers:(producers.data||[]) as never[],varieties:(varieties.data||[]) as never[],materials:(materials.data||[]) as never[],workers:(workers.data||[]) as never[]}}
  let operationRows:Record<string,unknown>[]=[];let operationChoices:Record<string,{id:number;nombre?:string;codigo?:string}[]>={};
  if(slug==="envios"){const [r,l,c,t]=await Promise.all([supabase.from("envio").select("*,lote(codigo),cliente(nombre),transportista(nombre)").eq("anulado",false).order("created_at",{ascending:false}),supabase.from("lote").select("id,codigo").eq("estado","LISTO").order("codigo"),supabase.from("cliente").select("id,nombre").eq("activo",true),supabase.from("transportista").select("id,nombre").eq("activo",true)]);operationRows=r.data||[];operationChoices={lots:l.data||[],clients:c.data||[],carriers:t.data||[]}}
  if(slug==="recepciones"){const [r,e,m,c]=await Promise.all([supabase.from("recepcion").select("*,envio(codigo),rechazo(id,cantidad,observaciones,motivo_rechazo(nombre),disposicion_rechazo(id,estado,cantidad))").order("fecha_recepcion",{ascending:false}),supabase.from("envio").select("id,codigo").eq("estado","ENVIADO").eq("anulado",false).order("codigo"),supabase.from("motivo_rechazo").select("id,nombre").eq("activo",true).order("nombre"),supabase.from("cliente").select("id,nombre").eq("activo",true).order("nombre")]);operationRows=r.data||[];operationChoices={shipments:e.data||[],reasons:m.data||[],clients:c.data||[]}}
  if(slug==="ventas"){const [v,r]=await Promise.all([supabase.from("venta").select("*,cliente(nombre)").order("fecha_venta",{ascending:false}),supabase.from("recepcion").select("id,envio(codigo)").eq("estado","CONFIRMADA")]);operationRows=v.data||[];operationChoices={receptions:(r.data||[]).map(x=>({id:x.id,codigo:`${Array.isArray(x.envio)?x.envio[0]?.codigo:x.envio?.codigo} · recepción ${x.id}`}))}}
  if(slug==="finanzas"){const [g,b,c,v,l,pb,profit,payments]=await Promise.all([supabase.from("gasto").select("*,categoria_gasto(nombre)").eq("anulado",false).order("fecha_gasto",{ascending:false}),supabase.from("v_saldo_venta").select("*").gt("saldo_pendiente",0),supabase.from("categoria_gasto").select("id,nombre").eq("activo",true),supabase.from("v_saldo_venta").select("venta_id,codigo").gt("saldo_pendiente",0),supabase.from("lote").select("id,codigo").eq("estado","LISTO").is("precio_productor_java",null).order("codigo"),supabase.from("v_saldo_productor").select("*").order("codigo"),supabase.from("v_rentabilidad_lote").select("*").order("codigo"),supabase.from("pago_venta").select("id,fecha_pago,monto,medio_pago,venta(codigo)").eq("anulado",false).order("fecha_pago",{ascending:false})]);operationRows=[...(g.data||[]).map(x=>({...x,kind:"expense"})),...(b.data||[]).map(x=>({...x,kind:"balance"})),...(pb.data||[]).map(x=>({...x,kind:"producerBalance"})),...(profit.data||[]).map(x=>({...x,kind:"profit"})),...(payments.data||[]).map(x=>({...x,kind:"payment"}))];operationChoices={categories:c.data||[],sales:(v.data||[]).map(x=>({id:x.venta_id,codigo:x.codigo})),withoutPrice:l.data||[]}}
  let profiles:Record<string,unknown>[]=[];if(slug==="administracion"){const {data}=await supabase.from("perfil_usuario").select("id,nombre,rol,activo,created_at").order("nombre");profiles=data||[]}
  const inMasters=slug==="maestros"||Boolean(table);const isOperation=["envios","recepciones","ventas","finanzas"].includes(slug);
  return <AppShell><header><div><p className="eyebrow">ERP Familia</p><h1>{title}</h1><p className="muted">Control simple y conectado de la operación frutícola.</p></div></header>{inMasters?<MasterTabs/>:null}{slug==="inicio"?<Dashboard/>:slug==="produccion"?<LotsManager {...lotData}/>:slug==="maestros"?<section className="masterGrid">{masters.map(({n,h,i:Icon})=><Link href={h} className="masterCard" key={h}><span><Icon/></span><div><h2>{n}</h2><p>Gestionar registros de {n.toLowerCase()}.</p></div><ArrowRight size={18}/></Link>)}</section>:table?<MasterManager table={table} title={title} rows={rows as never[]} products={products}/>:isOperation?<OperationsManager module={slug} rows={operationRows} choices={operationChoices}/>:slug==="administracion"?<section className="panel"><div className="panelHead"><div><h2>Usuarios y permisos</h2><p>Acceso actual al sistema.</p></div></div><div className="tableWrap"><table><thead><tr><th>Nombre</th><th>Rol</th><th>Estado</th></tr></thead><tbody>{profiles.map(p=><tr key={String(p.id)}><td>{String(p.nombre)}</td><td>{String(p.rol)}</td><td><span className={`status ${p.activo?"":"off"}`}>{p.activo?"Activo":"Inactivo"}</span></td></tr>)}</tbody></table></div></section>:null}</AppShell>
}
function Dashboard(){const cards=[{l:"Lotes activos",v:"—",i:Sprout},{l:"Envíos en tránsito",v:"—",i:Truck},{l:"Recepciones pendientes",v:"—",i:ClipboardCheck},{l:"Ventas del mes",v:"—",i:CircleDollarSign}];return <><section className="stats">{cards.map(({l,v,i:Icon})=><article key={l}><span><Icon/></span><div><p>{l}</p><strong>{v}</strong></div></article>)}</section><section className="panel flow"><Boxes/><div><h2>LOTE → ENVÍO → RECEPCIÓN → VENTA</h2><p>La columna vertebral operativa ya está reflejada en el esquema.</p></div></section></>}

